### ISSUE TITLE
async fn main

### ISSUE THREAD

**Issue by midnightexigent** [yuhr/fncmd#11]
Hi, 

It's common for `main` functions to look like this

```rs
#[tokio::main]
async fn main() -> anyhow::Result<()> {}
```

adding `#[fncmd]` to that doesn't work. is there planned support for that ?

**Comment by yuhr** [comment]
Going to implement this week, but a PR is also appreciated (I'm not much experienced with async programming in Rust).

**Comment by midnightexigent** [comment]
I can give it a shot, tho I have never worked on proc macro crates before

**Comment by yuhr** [comment]
This line seems to be invalid:

https://github.com/yuhr/fncmd/blob/260b1b84038ec5d3987471c3470e197cde8dfc41/impl/src/models/fncmd.rs#L186

`attrs` originally came from the `main` function's attributes, but they're attached to a struct in the macroexpanded form. Maybe moving this line to the top of `main` should solve the issue?

**Comment by midnightexigent** [comment]
Got it ! That was almost it 

There also needed to be an `#asyncness` in front of `fn main()`

Now this works

```rs 
use fncmd::fncmd;

/// Description of the command line tool
#[fncmd]
#[tokio::main]
pub async fn main(
    /// Argument foo
    #[opt(short, long)]
    foo: String,
    /// Argument bar
    #[opt(short, long)]
    bar: Option<String>,
) {
    println!("{:?} {:?}", foo, bar);
}

```

I opened #12
